#import tkinter and Hovertip
from tkinter import*
from idlelib.tooltip import Hovertip

class CustomHovertip(Hovertip):
    def showcontents(self):
        label = Label(
            self.tipwindow, text=f' "{self.text}" ',
            bg="yellow", fg="black",
            font=("Calibri", 12)
            )
        label.pack()

# Create new instance - class Tk()
root = Tk()
root.iconbitmap ('logo.ico')
root.title ("National team '74")
root.geometry ("810x655")
root.resizable (0, 0)
bgImage = PhotoImage (file = "img/soccer_field.png")
labelImage = Label (root, image = bgImage)
labelImage.place (x = 0, y = 0)

# col 0 goalkeeper (player/s 1)
col0 = Frame()
col0.grid( column = 0, row = 0, rowspan=4 )
col0.config(width = '160', height = '640', bg='')
one = PhotoImage (file = 'img/1.png')
label1 = Label (root, image = one)
label1.grid( column = 0, row = 0, rowspan=4, sticky="w")
CustomHovertip(label1, text="Daniel Carnevali", hover_delay=50)

# col 1 defense (player/s 4)
col1_0 = Frame()
col1_0.grid(column = 1, row = 0)
col1_0.config(width = '160', height = '160', bg='')
two = PhotoImage (file = 'img/2.png')
label2 = Label (root, image = two)
label2.grid( column = 1, row = 0, sticky="e")
CustomHovertip(label2, text="Chupete Guerini", hover_delay=50)

col1_1 = Frame()
col1_1.grid(column = 1, row = 1)
col1_1.config(width = '160', height = '160', bg='')
three = PhotoImage (file = 'img/3.png')
label3 = Label (root, image = three)
label3.grid( column = 1, row = 1, sticky="w")
CustomHovertip(label3, text="Roberto Telch", hover_delay=50)

col1_2 = Frame()
col1_2.grid(column = 1, row = 2)
col1_2.config(width = '160', height = '160', bg='')
four = PhotoImage (file = 'img/4.png')
label4 = Label (root, image = four)
label4.grid( column = 1, row = 2, sticky="w")
CustomHovertip(label4, text="Enrique Chazarreta", hover_delay=50)

col1_3 = Frame()
col1_3.grid(column = 1, row = 3)
col1_3.config(width = '160', height = '160', bg='')
five = PhotoImage (file = 'img/5.png')
label5 = Label (root, image = five)
label5.grid( column = 1, row = 3, sticky="e")
CustomHovertip(label5, text="Miguel Brindisi", hover_delay=50)

# col 2 midfielders (player/s 2)
col2_0 = Frame()
col2_0.grid(column = 2, row = 0, rowspan=2)
col2_0.config(width = '160', height = '320', bg='')
six = PhotoImage (file = 'img/6.png')
label6 = Label (root, image = six)
label6.grid( column = 2, row = 0, rowspan=2)
CustomHovertip(label6, text="Enrique Wolff", hover_delay=50)

col2_3 = Frame()
col2_3.grid(column = 2, row = 2, rowspan=2)
col2_3.config(width = '160', height = '320', bg='')
seven = PhotoImage (file = 'img/7.png')
label7 = Label (root, image = seven)
label7.grid( column = 2, row = 2, rowspan=2)
CustomHovertip(label7, text="Angel Bargas", hover_delay=50)

# col 3 middle forward (player/s 3)
col3_0 = Frame()
col3_0.grid(column = 3, row = 0)
col3_0.config(width = '160', height = '160', bg='')
eight = PhotoImage (file = 'img/8.png')
label8 = Label (root, image = eight)
label8.grid( column = 3, row = 0, sticky="e")
CustomHovertip(label8, text="Indio Correa", hover_delay=50)

col3_1 = Frame()
col3_1.grid(column = 3, row = 1, rowspan=2)
col3_1.config(width = '160', height = '320', bg='')
nine = PhotoImage (file = 'img/9.png')
label9 = Label (root, image = nine)
label9.grid( column = 3, row = 1, rowspan=2)
CustomHovertip(label9, text="Ramón 'Cacho' Heredia", hover_delay=50)

col3_2 = Frame()
col3_2.grid(column = 3, row = 3)
col3_2.config(width = '160', height = '160', bg='')
ten = PhotoImage (file = 'img/10.png')
label10 = Label (root, image = ten)
label10.grid( column = 3, row = 3, sticky="e")
CustomHovertip(label10, text="Agustín Balbuena", hover_delay=50)

# Goal scorer (player/s 1)
col4_0 = Frame()
col4_0.grid(column = 4, row = 0, rowspan=4 )
col4_0.config(width = '160', height = '160', bg='')
eleven = PhotoImage (file = 'img/11.png')
label11 = Label (root, image = eleven)
label11.grid( column = 4, row = 0, rowspan=4 )
CustomHovertip(label11, text="Rubén Ayala", hover_delay=50)

root.mainloop()